version: '3.7'

services:
  frontend:
    restart: on-failure
    build: .
    ports:
      - "3008:3002"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3008 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - elk
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  elk:
    driver: bridge