version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=poc-organization
      - DOCKER_INFLUXDB_INIT_BUCKET=poc-artillery.io
      - DOCKER_INFLUXDB_INIT_RETENTION=1w # 1 week
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - 8086:8086
    volumes:
      - influxdb2config:/etc/influxdb2
      - influxdb2data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8086/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  telegraf:
    image: telegraf:1.18
    depends_on:
      influxdb:
        condition: service_healthy
    restart: always
    environment:
      - INFLUX_DB2_HOST_ADDRESS=influxdb
      - INFLUX_DB2_TOKEN=my-super-secret-auth-token
      - INFLUX_DB2_ORGANIZATION=poc-organization
      - INFLUX_DB2_BUCKET=poc-artillery.io
    healthcheck:
      test: ["CMD-SHELL", "telegraf --test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8092:8092/udp
      - 8094:8094/tcp
      - 8125:8125/udp
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  influxdb2config:
  influxdb2data:
  grafana-storage: