version: '3.7'

networks:
  elk:
    driver: bridge
  default:
    driver: bridge

services:
  es_container_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es_container_1
    environment:
     - cluster.name=es_cluster
     - node.name=es_container_1
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
     - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Increase heap size
     - cluster.routing.allocation.disk.watermark.low=85%
     - cluster.routing.allocation.disk.watermark.high=90%
     - cluster.routing.allocation.disk.watermark.flood_stage=95%
     - discovery.seed_hosts=es_container_1,es_container_2,es_container_3
     - cluster.initial_master_nodes=es_container_1,es_container_2,es_container_3
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data_1:/usr/share/elasticsearch/data
    networks:
      - elk
  es_container_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es_container_2
    environment:
      - cluster.name=es_cluster
      - node.name=es_container_2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.seed_hosts=es_container_1,es_container_2,es_container_3
      - cluster.initial_master_nodes=es_container_1,es_container_2,es_container_3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data_2:/usr/share/elasticsearch/data
    networks:
      - elk

  es_container_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es_container_3
    environment:
      - cluster.name=es_cluster
      - node.name=es_container_3
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.seed_hosts=es_container_1,es_container_2,es_container_3
      - cluster.initial_master_nodes=es_container_1,es_container_2,es_container_3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data_3:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logger/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logger/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logs:/usr/share/logstash/data  
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - es_container_2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./logger/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
    depends_on:
      - es_container_2

volumes:
  es_data_1:
  es_data_2:
  es_data_3:
  grafana-storage:
  influxdb2config:
  influxdb2data:
