version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    restart: always
    networks:
      - elk
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=poc-organization
      - DOCKER_INFLUXDB_INIT_BUCKET=poc-artillery.io
      - DOCKER_INFLUXDB_INIT_RETENTION=1w # 1 week
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - 8086:8086
    volumes:
      - influxdb2config:/etc/influxdb2
      - influxdb2data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8086/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    restart: always
    networks:
      - elk
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  influxdb2config:
  influxdb2data:
  grafana-storage:

networks:
  elk:
    driver: bridge
  default:
    driver: bridge