global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "express-app"
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']

rule_files:
  - './alert_rules.yml' 